### ISSUE TITLE
Form validations

### ISSUE THREAD

**Issue by lussn** [lussn/coop#19]
- [x] Add new react bootstrap behavior
- [x] Form validation with bootstrap
- [x] Refactor form inputs
- [x] Backend sync - promises in the backend
- [x] Frontend sync - account edit,add,delete validations
- [x] Frontend sync - organization edit, add,delete validations

**Comment by lussn** [comment]
`/home/lucho/coop/application/OrganizationRegisterService.js:37
                throw new Error(err);
                ^

Error: UserExistsError: A user with the given username is already registered
    at /home/lucho/coop/application/OrganizationRegisterService.js:37:23
    at /home/lucho/coop/infrastructure/persistence/AccountsRepository.js:7:16
`
